apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: synapse-tempo
    isDefault: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: synapse-prometheus
      tracesToLogsV2:
        datasourceUid: ''
      tracesToMetrics:
        datasourceUid: synapse-prometheus
        tags:
          - key: service.name
            value: service_name
      nodeGraph:
        enabled: true
      spanBar:
        type: None
    version: 1
    editable: false
