export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  SYSTEMS: '/systems',
  ALERTS: '/alerts',
  CONTACTS: '/contacts',
  REPORTS: '/reports',
  REPORTS_HISTORY: '/reports/history',
  SEARCH: '/search',
  TRENDS: '/trends',
  FEEDBACK: '/feedback',
  FEEDBACK_SUBMIT: '/feedback/submit',
  FEEDBACK_SEARCH: '/feedback/search',
  PROFILE: '/profile',
  ADMIN_USERS: '/admin/users',
  VECTOR_HEALTH: '/vector-health',
  GRAFANA: '/grafana-dashboard',
  AGENTS: '/agents',
  systemDetail: (id: number | string) => `/dashboard/${id}`,
  agentDetail: (id: number | string) => `/agents/${id}`,
}
